### PR TITLE
Add key prop to Star component

### LINKED ISSUE #1: Throws a warning on render
v1.1.7

Screenshot for reference:

error

### PR DESCRIPTION
**Pull request by dakshkhetan**
fixes #1

### CODE REVIEW

**Review by vilvaathibanpb — COMMENTED** [review]
Hey @dakshkhetan ,

Thanks a lot for the PR. Can you add the prop details in docs/README as well?

**Comment by dakshkhetan** [comment]
I don't think any detail/documentation is required for the changes made in this PR.

**Comment by vilvaathibanpb** [comment]
My bad. Got it. Thanks for the PR. merging it :)

**Comment by dakshkhetan** [comment]
Hey @vilvaathibanpb, can you please update the npm package soon? (v1.1.7 -> v1.1.8)

**Comment by vilvaathibanpb** [comment]
@dakshkhetan  Done :)

**Comment by dakshkhetan** [comment]
@vilvaathibanpb `lib/Rating.js` is not updated. I guess you didn't build the project. Can you please look into it?

**Pull request merged**
